/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_appsync_graphqlEndpoint": "https://rgh46hzpm5h2xod3vurwir7b4q.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS",
    "aws_cognito_identity_pool_id": "us-east-1:fcf1ae24-2086-4ab1-89f1-40f0268f2ebc",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_k8CZRd9lL",
    "aws_user_pools_web_client_id": "3kogoapvhf6as71buu0jlvjcgp",
    "oauth": {}
};


export default awsmobile;
